services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: botari
      POSTGRES_USER: botari_user
      POSTGRES_PASSWORD: "G7@k8nPz#xL1w$$R4"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botari_user -d botari"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  web:
    build: .
    command: tail -f /dev/null  # ← Временная команда для диагностики (заменит gunicorn)
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    restart: unless-stopped  # Изменили на unless-stopped для диагностики

volumes:
  postgres_data:
