services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: botari
      POSTGRES_USER: botari_user
      POSTGRES_PASSWORD: "G7@k8nPz#xL1w$$R4"  # Явно указан пароль с экранированием $
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botari_user -d botari"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  web:
    build: .
    command: sh -c "while ! nc -z db 5432; do sleep 1; done && gunicorn --bind 0.0.0.0:8000 botari.wsgi:application"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    restart: always

volumes:
  postgres_data:
