services:
  web:
    build: .
    command: >
      sh -c "sleep 5 &&
      while ! nc -z db 5432; do sleep 1; done &&
      gunicorn --bind 0.0.0.0:8000 Botari.Botari.wsgi:application"
    environment:
      PYTHONPATH: "/app:/app/botari"  # Дублируем на случай compose
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
